nombreUsuario = input("Ingrese su nombre: ")
print()
numero1 = float(input("Insgrese el primer numero: "))
numero2 = float(input("Insgrese el primer numero: "))
print()
print("Hola ", nombreUsuario, ", el resultado de las operaciones son:")
print("Suma: ", numero1 + numero2)
print("Resta: ", numero1 - numero2)
print("Multiplicacion: ", numero1 * numero2)
print("Division: ", numero1 / numero2)
print("Division Entera: ", numero1 // numero2)
print("Potencia: ", numero1**numero2)